### PR TITLE
Upgrade helm to 3.6.3

### LINKED ISSUE #93: Upgrade to latest go helm libraries
### What problem are you facing?

With the jupyterhub helm chart, in the absence of some values, the following error is hit  `wrong type for value; expected map[string]interface {}; got interface {}``

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1998 Give more background on this.

For the record, Terraform helm provider was hitting the same problem (see details in the linked issue), and @chrisbulgaria  said on https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1998#issuecomment-849623237 `...  Think by upgrading to the latest version of some helm go libraries , so...`

### PR DESCRIPTION
**Pull request by turkenh**
### Description of your changes

Resolves #93

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

Run integration tests locally

### CODE REVIEW

**Comment by turkenh** [comment]
Build failing due to some dependency resolution problem as reported [here](https://github.com/kubernetes-sigs/kustomize/issues/3262).

```
# sigs.k8s.io/kustomize/pkg/transformers/config
roperties (type map[string]"k8s.io/kube-openapi/pkg/validation/spec".Schema) as type myProperties in argument to looksLikeAk8sType
```

There is still an open issue in cli-runtime: https://github.com/kubernetes/cli-runtime/issues/19
And some more details on the problem: https://github.com/kubernetes-sigs/kustomize/tree/master/cmd/depprobcheck

I could not find a workaround yet :/

**Comment by ctrox** [comment]
Had a look at this out of curiosity and I think the "simplest" solution here is to upgrade all k8s dependencies to ` v0.21` as described in the [kustomize repo](https://github.com/kubernetes-sigs/kustomize/tree/master/cmd/depprobcheck), this would also require an upgrade of `helm` and `controller-runtime` plus it would first require an upgrade to `v0.21.2` in `crossplane-runtime`. 

With that and a locally patched `controller-runtime` I got your branch to compile:

```diff
diff --git a/go.mod b/go.mod
index 9cdd90f..052dcd6 100644
--- a/go.mod
+++ b/go.mod
@@ -3,16 +3,16 @@ module github.com/crossplane-contrib/provider-helm
 go 1.16
 
 require (
        github.com/crossplane/crossplane-runtime v0.13.0
        github.com/crossplane/crossplane-tools v0.0.0-20210320162312-1baca298c527
-       github.com/google/go-cmp v0.5.2
+       github.com/google/go-cmp v0.5.6
        github.com/pkg/errors v0.9.1
        gopkg.in/alecthomas/kingpin.v2 v2.2.6
-       helm.sh/helm/v3 v3.5.4
-       k8s.io/api v0.20.4
-       k8s.io/apimachinery v0.20.4
-       k8s.io/client-go v0.20.4
-       sigs.k8s.io/controller-runtime v0.8.3
+       helm.sh/helm/v3 v3.6.1
+       k8s.io/api v0.21.2
+       k8s.io/apimachinery v0.21.2
+       k8s.io/client-go v0.21.2
+       sigs.k8s.io/controller-runtime v0.9.2
        sigs.k8s.io/controller-tools v0.5.0
        sigs.k8s.io/kustomize/api v0.8.10
        sigs.k8s.io/kustomize/kyaml v0.10.20
@@ -21,6 +21,7 @@ require (
 
 // See https://github.com/helm/helm/blob/release-3.5/go.mod#L51
 replace (
+       github.com/crossplane/crossplane-runtime => /local/path/patched-crossplane-runtime
        github.com/docker/distribution => github.com/docker/distribution v0.0.0-20191216044856-a8371794149d
        github.com/docker/docker => github.com/moby/moby v17.12.0-ce-rc1.0.20200618181300-9dc6525e6118+incompatible
 )
```

**Comment by turkenh** [comment]
@ctrox thanks for trying that out.

Actually, there is an open PR in crossplane runtime for that: https://github.com/crossplane/crossplane-runtime/pull/267, and I could build using that as well.

**Review by hasheddan — APPROVED** [review]
LGTM!

**Pull request merged**
